### ISSUE TITLE
Bushmaster Texture - UN Variant

### ISSUE THREAD

**Issue by IsoBones** [IsoBones/ADFRC#113]
From Discord:
Suggestion: United Nations Bushmaster variant

Why: this version of the bushmaster would allow for more Australian oriented United Nations ops and would just be an awesome look for the Bushmaster 

A good view of this can be found in the below video;

https://youtu.be/T4PtVWowuds?si=4ovox-Q4sR8u-U2b

**Comment by Quiggsleyy** [comment]
Added to garage
