### ISSUE TITLE
Rework Bushmaster Camo Colours

### ISSUE THREAD

**Issue by Quiggsleyy** [IsoBones/ADFRC#122]
In line with IsoBones/ADFRC#145, complete colour correction to be more inline with ASLAV set, with further tweaks.

**Comment by Quiggsleyy** [comment]
- UV map reviewed, working correctly no need for UV's to be redone, interior is on its own set so for future variants options can just be added as proxys or hiddenselections depending on the model, saving from creating duplicate models. 
- Base camo set completed.

Whats next:

- Complete height map, dirt, wear and tear, and other details for textures.
- Add proxy for damage model and complete config to suit.

**Comment by IsoBones** [comment]
Done in IsoBones/ADFRC#137
