### ISSUE TITLE
Implement M1A1AIM MBT

### ISSUE THREAD

**Issue by IsoBones** [IsoBones/ADFRC#127]
Implement a slightly updated Arma 2 port of the M1A1 Abrams MBT, with additions to upgrade it to our ADF AIM variant

**Comment by Quiggsleyy** [comment]
Current stage

Model imported, Phyx & config base completed, working animations and voxels,

Needs doing:

Textures created
Model updated (started)
Config adjusted to use mod ammo
Sounds updated to use A3 sounds

**Comment by Quiggsleyy** [comment]
Model extras added.

-Roadwheel to roof.
-NBC filter on turret.
-Tow ropes created & mounted on turret.
-Torsion bars updated.
-Added extra shafts for idler pulley & drive sprocket.

**Comment by Quiggsleyy** [comment]
Model updated:

Last update also included a bustle rack extension on the rear of turret

- Side road wheels mounted on rack
- Turret unit markings added
Added storage bin to rear of turret
- Added jerry can holders to rack
- Loaders Mag58 added with mount system and rigged for movement
- loaders periscope modelled to be moveable 
- Turret mesh optimisation
- Rear of hull mesh updated
- Added tow hitch 
- vents are modelled into engine cover.
- hull tow rings and hatch hinges
- Taillights scaled to correct size
- Decal placeholders set for tank names

**Comment by Quiggsleyy** [comment]
- Updated Mag58 to coax handle
- imported higher quality M2 .50 for commander
- Commanders cupola updated to AIM model version
- Corrected mesh issues with inverted normals, more optimised
- Regrouped objects to be hidden selections

**Comment by Quiggsleyy** [comment]
Decision made to scrap arma 2 model in favour for higher quality model held within mod archive. (M1A1AIM)
- 18k < 37k verts 

Most features added to to A2 model are already present on new model, however M2 & MAG58 additions ported over and set

Decision made as although model needs to be configured more, it'll create a smoother workflow to implement & with a much better model in game.

**Comment by Quiggsleyy** [comment]
- Rescaled new Abrams & ports to be their correct size
- All vertex groups set for base model
- Hidden Selections mods added
- Materials list set for applicable groups to use in Substance
- Further optimisation to .50 & MAG58

Whats next:
- Add more customisation options for hidden selections 
[with CUP & RHS style additions
in mind + unique camo burlap straps used by ADF]
- Create UV maps 
- Define proxys & rig model 
- Set Geo, fire & shadow LODS once model additions complete

**Comment by Quiggsleyy** [comment]
Base camo started, weathering and damage details being trialed for smoother workflow. 

To be refined further, details to be added next

**Comment by Quiggsleyy** [comment]
More mesh optimisation completed, fixed some non-welded vertices.  

M2QCB & MAG58 removed for further optimisation as poly count alone makes up the half of total amount.

**Comment by Quiggsleyy** [comment]
Added more hidden selection customization options, camo net planes & UV map optimized, updated optics model to have opacity with lenses, finished UV maps.

**_Whats next_**

Re-add optimized MAG58 & M2QCB
Finish defining vertex groups for Object Builder
Define proxys & rig model
Set Geo, fire & shadow LODS

**Comment by Quiggsleyy** [comment]
Added additional customisation options in the form of deployment gear and equipment plus a mine plow. 

Smoke launchers updated

Re-added optimised M2 & MAG58 with proper mounts further updates to commanders cupola.

More vertex groups defined.
