### ISSUE TITLE
Faction overhaul

### ISSUE THREAD

**Issue by IsoBones** [IsoBones/ADFRC#150]
Ties in to issue IsoBones/ADFRC#169 
Remake faction to incorporate accurate loadouts for Army, 2Commando and SASR
Create new invisible faction, structure faction so that ALiVE is compatible with it (Only include Army inf/vehicles, SASR as Special Forces subcategory)
The two factions should not clash with each other, and the ALiVE faction should not be visible in the editor. Only the `ADFU` faction should be visible in editor as `ADF`.

Work has already begun on this issue.

**Comment by sgtfuzzle17** [comment]
To keep stuff documented, new faction (Men) names should display as (old then new):
DPCU > (Men) Australian Army
DPDU > (Men) 2nd Commando Regiment
AMP > (Men) Special Air Service Regiment

**Comment by IsoBones** [comment]
Just needs IsoBones/ADFRC#157 finished and we are done here
