### ISSUE TITLE
Allow ADFU optics to be mounted on any (basegame) optic rails

### ISSUE THREAD

**Issue by sgtfuzzle17** [IsoBones/ADFRC#153]
Currently the optics from ADFU can't be mounted on standard Arma 3 rails, which is a blocker to implement a proper HK417 Designated Marksman (none of the optics currently compatible with the 417 work as stand-ins for in-service optics).

**Comment by sgtfuzzle17** [comment]
Note that once this is completed, if the new loadout/naming conventions are also implemented, the Designated Marksman `ADFU_marksman_dpcu` should have the ACOG TA648 with RDS swapped onto the 417 to better reflect real world usage.

**Comment by IsoBones** [comment]
Monumental amount of work required to implement this, closing as not currently planned.
