### ISSUE TITLE
Have ASLAV (MAG-58)'s commander's head follow point of aim

### ISSUE THREAD

**Issue by sgtfuzzle17** [IsoBones/ADFRC#155]
Currently the ASLAV (MAG-58)'s commander doesn't actually track his point of aim. Would be nice if he looked where he was shooting.
![3Kybk7g](https://user-images.githubusercontent.com/49757384/236616245-8688f708-5fac-4888-a46c-e9a16c66b5fa.jpg)

**Comment by IsoBones** [comment]
I'll have a look into it, might not be too hard

**Comment by IsoBones** [comment]
@Barais20 Is this something we can actually do?

**Comment by IsoBones** [comment]
This works for any crew that's turned out not using a weapon. Unfortunately even in big mods they haven't found a way around this issue with MG's that don't have the entire cupula move around as well.
