### ISSUE TITLE
Bug: no turn in option for ASLAV crew

### ISSUE THREAD

**Issue by sgtfuzzle17** [IsoBones/ADFRC#156]
By default, ASLAV crews are turned out with no way to turn in. Occurs in both the commander and driver position (see screenshots for driver).
![aUfLyYW](https://user-images.githubusercontent.com/49757384/236615950-0ca8968a-d7c8-4cf3-8162-c2a0e20884cb.jpg)
![mmE61pC](https://user-images.githubusercontent.com/49757384/236615958-392c1aee-33d8-4b93-bf0f-1ba21aa29218.jpg)

**Comment by sgtfuzzle17** [comment]
For posterity, this is only an issue when running the current version of the JSRS compat, likely due to some old code which snuck into that mod's config.cpp. Recommend having a look at merging the non-compat related portion of the newer main branch config into the JSRS branch.

**Comment by IsoBones** [comment]
Issue was fixed within JSRS patch
