### ISSUE TITLE
New asset: Ballistic Glasses

### ISSUE THREAD

**Issue by sgtfuzzle17** [IsoBones/ADFRC#162]
Currently we have no good facewear options for glasses; the basegame glasses both have little sci-fi AR panels on them. Below is a reference for a good set that can often be seen worn by ADF troops in the field.

![wiley-x-saber__84565__73010](https://user-images.githubusercontent.com/49757384/235841861-48391597-786c-418e-abc9-32f793aed315.jpg)

**Comment by IsoBones** [comment]
Implementation of the Kondor glasses resolves this
