### ISSUE TITLE
Unit cfgEditorSubCategories change to type instead of camo

### ISSUE THREAD

**Issue by sgtfuzzle17** [IsoBones/ADFRC#169]
Leaving issue as requested by @IsoBones 

For unit categories (cfgEditorSubCategories), group units by operational type rather than just camo. This will allow better differentiation for end users on equipment/doctrinal differences, as well as allowing specific units to be built (ie an Australian Army having F88s, while SASR may be using M4A5s). 

Categories would be:

- Australian Army
- Special Air Service Regiment
- 2nd Commando Regiment

Each of these would effectively function as "Men" categories. Vehicles can draw their units from crew classnames within the Australian Army category.

**Comment by IsoBones** [comment]
I've done some more research on this, specifically from [this website](https://www.camopedia.org/index.php/Australia)
I believe we will need to sit down at some point and actually figure out where/who each pattern was for.

May also be a bit harder to separate stuff like the overalls and pilot gear as it is all wrapped up in AMP stuff

**Comment by IsoBones** [comment]
Now a part of IsoBones/ADFRC#150
