### ISSUE TITLE
Create ACE Compat Patch

### ISSUE THREAD

**Issue by IsoBones** [IsoBones/ADFRC#170]

**Comment by IsoBones** [comment]
To Do:
- MRH-90
- C-130

**Comment by IsoBones** [comment]
**High Priority**
ACE Medical no longer works with ADF:RC uniforms/vests
@wolfendragoon will investigate

**Comment by IsoBones** [comment]
@wolfendragoon Please look into implementation of ACE Medical compat into the main mod structure as a part of Issue IsoBones/ADFRC#137 
We can roll out the included compat patch with the new codebase

**Comment by IsoBones** [comment]
Ace Compat Patch to be rolled into main mod now.

**Comment by wolfendragoon** [comment]
Updated Ace Compat config files sent to IsoBones for review. Future updates to Ace Compatibility will be main in the main mod.
