### ISSUE TITLE
MAG58 Proxy LOD Issue - S70 Blackhawk

### ISSUE THREAD

**Issue by IsoBones** [IsoBones/ADFRC#82]
Per [Discord submission](https://discord.com/channels/1099486374303903827/1292508066226507786)
Seems to only appear on the mag-58 version and appears when at a certain distance away, it only goes away when within 50-100 meters - video explains it better.
Also one when the helicopter is in flight that rotates with the main rotor (only the mag58 version as well)

https://github.com/user-attachments/assets/f5ab4eb8-5501-4ec8-b7b9-5a11ff49f37e

https://github.com/user-attachments/assets/99f3e042-fe6c-437d-8bb0-d14984cfc211

**Comment by BruceyADFR** [comment]
Looking at this one, I've checked the Mag58 and I can't spot any issues there. I've replaced the proxy (White triangle) in the model for the optics slot on all LODs, I'll assess ingame if this has fixed. 

If it has not, then it's a bad proxy on a LOD in the blackhawk itself, NOT the Mag58.

**Comment by BruceyADFR** [comment]
Replaced all proxies from LOD0 on MAG58 Blackhawk, will upload to factions branch with next push. 

Noted: LOD4 did NOT have a proxy at all (Final, lowest res lod), so added this back as I felt it was appropriate.
